name: loyalty_back
description: A backend server for loyalty cards app
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.1
  shelf_cors_headers: ^0.1.4
  dart_jsonwebtoken: ^2.7.0
  dotenv: ^4.2.0
  bcrypt: ^1.1.3
  uuid: ^4.0.0
  mime: ^1.0.4
  mongo_dart: ^0.10.0
  intl: ^0.20.2
  http: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  shelf_hotreload: ^1.0.0 # заменили версию
